### ISSUE TITLE
The Extension Cannot be Installed on Windows?

### ISSUE THREAD

**Issue by MinuraPunchihewa** [mindsdb/mindsdb-docker-extension#10]

**Comment by martyna-mindsdb** [comment]
Installing the extension:

![image](https://github.com/mindsdb/mindsdb-docker-extension/assets/109554435/99cc836b-d71d-49e1-97e2-edf0662b8afb)

Error notification:

![image](https://github.com/mindsdb/mindsdb-docker-extension/assets/109554435/1a9f948b-ee19-4055-bb53-0803f9b76cf1)

Full error message:

![image](https://github.com/mindsdb/mindsdb-docker-extension/assets/109554435/f65088b0-f6ce-49c0-9748-70db9e472357)

**Comment by martyna-mindsdb** [comment]
Tried using Docker Desktop v4.29.0 (previously used 4.28.0), but getting the same error:

![image](https://github.com/mindsdb/mindsdb-docker-extension/assets/109554435/37da497c-bce9-41d1-b0f6-aa1e8e694f4d)

**Comment by Leunam1392** [comment]
Exist other MindsDB extension in Docker Desktop for Windows 10 Home?

**Comment by MinuraPunchihewa** [comment]
Hey @Leunam1392,
Are you having trouble installing it as well?

**Comment by Leunam1392** [comment]
Problem solved, really thanks guys for the help.

**Comment by martyna-mindsdb** [comment]
You're welcome @Leunam1392

**Comment by martyna-mindsdb** [comment]
@MinuraPunchihewa 
Please close this issue. Thanks.

**Comment by MinuraPunchihewa** [comment]
Completed by https://github.com/mindsdb/mindsdb/pull/9146
