### ISSUE TITLE
Validate adjustments to information architecture in tree view

### ISSUE THREAD

**Issue by Dav1dF** [mindsdb/mindsdb-docker-extension#31]
Schedule and synthesise findings from task-based usability testing as discussed here [https://mindsdb.slack.com/archives/C075NQP4P41/p1716828637807429](https://mindsdb.slack.com/archives/C075NQP4P41/p1716828637807429)

3 usability tests were conducted ([details here](https://rajah-chough-hxjj.dovetail.com/projects/3nxIUK21c0vPwGTlqU8MTC/v/25cAN4C5acbXFnyvTal5KL))

[Prototype is located here](https://www.figma.com/design/rhmhpsquzT9dj7GRwzrhHN/Menu-tree-Q2.24?node-id=4131-13273&t=xnV7vU4sjMI5t5z5-1)

Design exploration [here](https://www.figma.com/design/rhmhpsquzT9dj7GRwzrhHN/Menu-tree-Q2.24?node-id=4069-2483&t=xnV7vU4sjMI5t5z5-1) and [here](https://www.figma.com/design/rhmhpsquzT9dj7GRwzrhHN/Menu-tree-Q2.24?node-id=4104-2150&t=xnV7vU4sjMI5t5z5-1)

[Child story for UI specs](https://github.com/mindsdb/mindsdb-frontend/issues/2815
)

**Comment by zac-mindsDB** [comment]
@Dav1dF is this the right place for these issues?  I can't seem to edit.
