### ISSUE TITLE
The Extension Binds the Ports Used by MindsDB

### ISSUE THREAD

**Issue by MinuraPunchihewa** [mindsdb/mindsdb-docker-extension#7]
When the extension is running on Docker Desktop, the ports that are used by MindsDB (specifically 47334 and 47335), are bound on the host machine. The reason for this is the fact that the extension runs the MindsDB container under-the-hood. Binding these ports make it unfeasible to run MindsDB via another means, locally (through Docker, PIP or from source code).

This may not cause many problems for users as they will probably only try a single method of running MindsDB, but it might hinder development unless users are aware of this. It might also be a problem for someone who is exploring the various methods available for running MindsDB.

Another minor, but connected issue here is that the extension also binds port 8080 incorrectly. There is no requirement for this to use MindsDB and should be fixed.

**Comment by MinuraPunchihewa** [comment]
Only partially resolved by https://github.com/mindsdb/mindsdb-docker-extension/pull/12

**Comment by Leunam1392** [comment]
Problem solved, thanks you guys for your help.
